/**
 * Development market-data universe.
 *
 * A representative but expandable universe of NSE equities + indices used by
 * the development provider. This is NOT a claim of live coverage: prices are
 * synthetically generated (data_source=development). When a licensed market
 * data feed is connected, the full instrument master replaces this file and
 * the radar universe grows to the complete NSE/BSE/F&O set — the architecture
 * does not depend on this list.
 */

export const DEVELOPMENT_UNIVERSE = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy', basePrice: 2450 },
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'IT', basePrice: 3250 },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking', basePrice: 1480 },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT', basePrice: 1350 },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking', basePrice: 1120 },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking', basePrice: 660 },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom', basePrice: 1120 },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking', basePrice: 1680 },
  { symbol: 'ITC', name: 'ITC Limited', sector: 'FMCG', basePrice: 355 },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Infrastructure', basePrice: 3210 },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Banking', basePrice: 940 },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG', basePrice: 2230 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Financial Services', basePrice: 6150 },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Auto', basePrice: 10400 },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Consumer Durables', basePrice: 2960 },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Consumer Durables', basePrice: 2850 },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT', basePrice: 375 },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT', basePrice: 1480 },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement', basePrice: 9550 },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical', sector: 'Pharma', basePrice: 1360 },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Conglomerate', basePrice: 2050 },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ', sector: 'Infrastructure', basePrice: 1180 },
  { symbol: 'POWERGRID', name: 'Power Grid Corp', sector: 'Power', basePrice: 285 },
  { symbol: 'NTPC', name: 'NTPC Limited', sector: 'Power', basePrice: 320 },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Auto', basePrice: 780 },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals', basePrice: 145 },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals', basePrice: 860 },
  { symbol: 'TATAPOWER', name: 'Tata Power', sector: 'Power', basePrice: 340 },
  { symbol: 'DIVISLAB', name: 'Divi\'s Laboratories', sector: 'Pharma', basePrice: 4850 },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma', basePrice: 1450 },
  { symbol: 'GRASIM', name: 'Grasim Industries', sector: 'Cement', basePrice: 2450 },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance', sector: 'Insurance', basePrice: 540 },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Insurance', basePrice: 1320 },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking', basePrice: 820 },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Financial Services', basePrice: 1460 },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Auto', basePrice: 7800 },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Auto', basePrice: 4450 },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Auto', basePrice: 4520 },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', sector: 'Auto', basePrice: 2350 },
  { symbol: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG', basePrice: 23200 },
  { symbol: 'BRITANNIA', name: 'Britannia Industries', sector: 'FMCG', basePrice: 5350 },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products', sector: 'FMCG', basePrice: 880 },
  { symbol: 'DMART', name: 'Avenue Supermarts', sector: 'Retail', basePrice: 3850 },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Healthcare', basePrice: 5800 },
  { symbol: 'DRREDDY', name: 'Dr. Reddy\'s Labs', sector: 'Pharma', basePrice: 5850 },
  { symbol: 'UPL', name: 'UPL Limited', sector: 'Agrochemicals', basePrice: 485 },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries', sector: 'Chemicals', basePrice: 2780 },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT', basePrice: 1240 },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Energy', basePrice: 415 },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp', sector: 'Energy', basePrice: 255 },
  { symbol: 'BPCL', name: 'Bharat Petroleum', sector: 'Energy', basePrice: 295 },
  { symbol: 'IOC', name: 'Indian Oil Corp', sector: 'Energy', basePrice: 135 },
  { symbol: 'GAIL', name: 'GAIL (India)', sector: 'Energy', basePrice: 175 },
  { symbol: 'HAL', name: 'Hindustan Aeronautics', sector: 'Defence', basePrice: 3050 },
  { symbol: 'BEL', name: 'Bharat Electronics', sector: 'Defence', basePrice: 210 },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals', sector: 'Power', basePrice: 285 },
  { symbol: 'VEDL', name: 'Vedanta', sector: 'Metals', basePrice: 415 },
  { symbol: 'HINDZINC', name: 'Hindustan Zinc', sector: 'Metals', basePrice: 455 },
  { symbol: 'DLF', name: 'DLF Limited', sector: 'Real Estate', basePrice: 640 },
  { symbol: 'GODREJPROP', name: 'Godrej Properties', sector: 'Real Estate', basePrice: 2350 },
  { symbol: 'SIEMENS', name: 'Siemens', sector: 'Capital Goods', basePrice: 5300 },
  { symbol: 'ABB', name: 'ABB India', sector: 'Capital Goods', basePrice: 6600 },
  { symbol: 'BOSCHLTD', name: 'Bosch', sector: 'Auto Ancillary', basePrice: 26500 },
  { symbol: 'HAVELLS', name: 'Havells India', sector: 'Consumer Durables', basePrice: 1480 },
  { symbol: 'CROMPTON', name: 'Crompton Greaves', sector: 'Consumer Durables', basePrice: 295 },
  { symbol: 'DIXON', name: 'Dixon Technologies', sector: 'Consumer Durables', basePrice: 7200 },
  { symbol: 'VOLTAS', name: 'Voltas', sector: 'Consumer Durables', basePrice: 1080 },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements', sector: 'Cement', basePrice: 520 },
  { symbol: 'SHREECEM', name: 'Shree Cement', sector: 'Cement', basePrice: 23800 },
  { symbol: 'DABUR', name: 'Dabur India', sector: 'FMCG', basePrice: 510 },
  { symbol: 'MARICO', name: 'Marico', sector: 'FMCG', basePrice: 545 },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive', sector: 'FMCG', basePrice: 2530 },
  { symbol: 'GODREJCP', name: 'Godrej Consumer', sector: 'FMCG', basePrice: 1120 },
  { symbol: 'ATUL', name: 'Atul Ltd', sector: 'Chemicals', basePrice: 6550 },
  { symbol: 'SRF', name: 'SRF Limited', sector: 'Chemicals', basePrice: 2450 },
  { symbol: 'PAGEIND', name: 'Page Industries', sector: 'Textiles', basePrice: 37500 },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', sector: 'Banking', basePrice: 225 },
  { symbol: 'CANBK', name: 'Canara Bank', sector: 'Banking', basePrice: 98 },
  { symbol: 'PNB', name: 'Punjab National Bank', sector: 'Banking', basePrice: 92 },
  { symbol: 'UNIONBANK', name: 'Union Bank of India', sector: 'Banking', basePrice: 118 },
  { symbol: 'IDEA', name: 'Vodafone Idea', sector: 'Telecom', basePrice: 12.5 },
  { symbol: 'ZEEL', name: 'Zee Entertainment', sector: 'Media', basePrice: 132 },
  { symbol: 'PTC', name: 'PTC India', sector: 'Power', basePrice: 145 },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland', sector: 'Auto', basePrice: 168 },
  { symbol: 'EXIDEIND', name: 'Exide Industries', sector: 'Auto Ancillary', basePrice: 365 },
  { symbol: 'MOTHERSON', name: 'Samvardhana Motherson', sector: 'Auto Ancillary', basePrice: 142 },
  { symbol: 'NYKAA', name: 'FSN E-Commerce (Nykaa)', sector: 'Retail', basePrice: 155 },
  { symbol: 'PAYTM', name: 'One 97 Communications', sector: 'Financial Services', basePrice: 535 },
  { symbol: 'ZOMATO', name: 'Eternal (Zomato)', sector: 'Internet', basePrice: 178 },
  { symbol: 'JIOFIN', name: 'Jio Financial Services', sector: 'Financial Services', basePrice: 285 },
  { symbol: 'LTIINDIA', name: 'LTIMindtree', sector: 'IT', basePrice: 5350 },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance', sector: 'Financial Services', basePrice: 1380 },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment', sector: 'Financial Services', basePrice: 1040 },
  { symbol: 'LICI', name: 'Life Insurance Corp', sector: 'Insurance', basePrice: 720 },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance', sector: 'Financial Services', basePrice: 1980 },
  { symbol: 'TVSMOTOR', name: 'TVS Motor', sector: 'Auto', basePrice: 1820 },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries', sector: 'Auto Ancillary', basePrice: 2480 },
  { symbol: 'MRF', name: 'MRF Limited', sector: 'Auto Ancillary', basePrice: 118000 },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation', sector: 'Aviation', basePrice: 3350 },
  { symbol: 'PERSISTENT', name: 'Persistent Systems', sector: 'IT', basePrice: 4450 },
  { symbol: 'COFORGE', name: 'Coforge', sector: 'IT', basePrice: 5250 },
  { symbol: 'MPHASIS', name: 'Mphasis', sector: 'IT', basePrice: 2450 },
  { symbol: 'BAJAJHLDNG', name: 'Bajaj Holdings', sector: 'Financial Services', basePrice: 8450 },
  { symbol: 'HINDALCO', name: 'Hindalco Industries', sector: 'Metals', basePrice: 575 },
  { symbol: 'NMDC', name: 'NMDC Limited', sector: 'Metals', basePrice: 178 },
  { symbol: 'SAIL', name: 'Steel Authority of India', sector: 'Metals', basePrice: 98 },
  { symbol: 'IRCTC', name: 'IRCTC', sector: 'Travel', basePrice: 890 },
  { symbol: 'POLYCAB', name: 'Polycab India', sector: 'Capital Goods', basePrice: 4450 },
  { symbol: 'CG', name: 'CG Power', sector: 'Capital Goods', basePrice: 385 },
  { symbol: 'AMBER', name: 'Amber Enterprises', sector: 'Consumer Durables', basePrice: 3950 },
  { symbol: 'SUPREMEIND', name: 'Supreme Industries', sector: 'Chemicals', basePrice: 4150 },
  { symbol: 'ABCAPITAL', name: 'Aditya Birla Capital', sector: 'Financial Services', basePrice: 175 },
  { symbol: 'BERGEPAINT', name: 'Berger Paints', sector: 'Consumer Durables', basePrice: 545 },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite', sector: 'Chemicals', basePrice: 2280 },
  { symbol: 'NAUKRI', name: 'Info Edge (Naukri)', sector: 'Internet', basePrice: 4850 },
  { symbol: 'DLINKINDIA', name: 'D-Link India', sector: 'Telecom', basePrice: 295 },
  { symbol: 'EMAMILTD', name: 'Emami', sector: 'FMCG', basePrice: 475 },
  { symbol: 'LALPATHLAB', name: 'Dr Lal PathLabs', sector: 'Healthcare', basePrice: 2150 },
  { symbol: 'METROPOLIS', name: 'Metropolis Healthcare', sector: 'Healthcare', basePrice: 1720 },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare', sector: 'Healthcare', basePrice: 850 },
  { symbol: 'HONAUT', name: 'Honeywell Automation', sector: 'Capital Goods', basePrice: 38500 },
  { symbol: 'THERMAX', name: 'Thermax', sector: 'Capital Goods', basePrice: 3750 },
  { symbol: 'AKZOINDIA', name: 'Akzo Nobel India', sector: 'Chemicals', basePrice: 2850 },
  { symbol: 'ESCORTS', name: 'Escorts Kubota', sector: 'Auto', basePrice: 3650 },
  { symbol: 'MAHINDICK', name: 'M&M Financial Services', sector: 'Financial Services', basePrice: 285 },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks', sector: 'Retail', basePrice: 545 },
  { symbol: 'UBL', name: 'United Breweries', sector: 'FMCG', basePrice: 1780 },
  { symbol: 'MCDOWELL-N', name: 'United Spirits', sector: 'FMCG', basePrice: 1080 },
  { symbol: 'SUNTV', name: 'Sun TV Network', sector: 'Media', basePrice: 565 },
  { symbol: 'TATACOMM', name: 'Tata Communications', sector: 'Telecom', basePrice: 1520 },
  { symbol: 'CUMMINSIND', name: 'Cummins India', sector: 'Capital Goods', basePrice: 2250 },
  { symbol: 'LTIM', name: 'LTI', sector: 'IT', basePrice: 4850 },
];

export const DEVELOPMENT_INDICES = [
  { symbol: 'NIFTY', name: 'Nifty 50', sector: 'Index', basePrice: 24500 },
  { symbol: 'NIFTYBANK', name: 'Nifty Bank', sector: 'Index', basePrice: 52500 },
  { symbol: 'SENSEX', name: 'BSE Sensex', sector: 'Index', basePrice: 81000 },
  { symbol: 'FINNIFTY', name: 'Nifty Financial Services', sector: 'Index', basePrice: 23800 },
];

export const DEVELOPMENT_FUTURES = [
  'RELIANCE',
  'TCS',
  'HDFCBANK',
  'INFY',
  'ICICIBANK',
  'SBIN',
  'ITC',
  'LT',
  'TATAMOTORS',
  'BAJFINANCE',
];

export const NIFTY_PLUS = [
  'RELIANCE', 'TCS', 'HDFCBANK', 'INFY', 'ICICIBANK', 'SBIN', 'BHARTIARTL',
  'KOTAKBANK', 'ITC', 'LT', 'AXISBANK', 'HINDUNILVR', 'BAJFINANCE', 'MARUTI',
  'ASIANPAINT', 'TITAN', 'WIPRO', 'HCLTECH', 'ULTRACEMCO', 'SUNPHARMA',
  'ADANIENT', 'ADANIPORTS', 'POWERGRID', 'NTPC', 'TATAMOTORS', 'TATASTEEL',
  'JSWSTEEL', 'DIVISLAB', 'CIPLA', 'GRASIM', 'HDFCLIFE', 'SBILIFE',
  'INDUSINDBK', 'BAJAJFINSV', 'BAJAJ-AUTO', 'EICHERMOT', 'HEROMOTOCO', 'M&M',
  'NESTLEIND', 'BRITANNIA', 'TATACONSUM', 'DMART', 'APOLLOHOSP', 'DRREDDY',
  'UPL', 'PIDILITIND', 'TECHM', 'COALINDIA', 'ONGC', 'BPCL',
];

export const INDEX_SYMBOLS = new Set(DEVELOPMENT_INDICES.map((i) => i.symbol));